---
deployment:
  tasks:
    - export DEPLOY_PATH=/home4/hg1cef63/public_html
    - /usr/bin/rsync -rltgoDz --delete ./dist/ $DEPLOY_PATH/
    - /bin/cp -f ./.htaccess $DEPLOY_PATH/.htaccess
    - /bin/touch $DEPLOY_PATH/.last_deploy_`date +%s`